robot:
    # Publish all joint states
    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50

    # Wheel Controllers
    left_centre_wheel_controller:
        type: effort_controllers/JointEffortController
        joint: left_centre_wheel_hinge
        pid: {p: 100.0, i: 0.1, d: 10.0}
    right_centre_wheel_controller:
        type: effort_controllers/JointEffortController
        joint: right_centre_wheel_hinge
        pid: {p: 100.0, i: 0.1, d: 10.0}
